export const ACHIEVEMENT_DEFINITIONS = [
  {
    id: 'first-step',
    name: 'First Step',
    description: 'Complete your first habit',
    icon: '🎯',
    target: 1,
    category: 'completion' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'habit-builder',
    name: 'Habit Builder',
    description: 'Complete 10 total habits',
    icon: '🏗️',
    target: 10,
    category: 'completion' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'dedication',
    name: 'Dedication',
    description: 'Complete 50 total habits',
    icon: '💪',
    target: 50,
    category: 'completion' as const,
    tier: 'silver' as const,
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Complete 100 total habits',
    icon: '🚀',
    target: 100,
    category: 'completion' as const,
    tier: 'gold' as const,
  },
  {
    id: 'consistency-king',
    name: 'Consistency King',
    description: 'Complete 500 total habits',
    icon: '👑',
    target: 500,
    category: 'completion' as const,
    tier: 'platinum' as const,
  },
  {
    id: 'milestone-1000',
    name: 'Legendary',
    description: 'Complete 1,000 total habits',
    icon: '🏅',
    target: 1000,
    category: 'completion' as const,
    tier: 'diamond' as const,
  },
  {
    id: 'week-warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    target: 7,
    category: 'streak' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'two-week-streak',
    name: 'Fortnight Fighter',
    description: 'Maintain a 14-day streak',
    icon: '⚡',
    target: 14,
    category: 'streak' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'month-master',
    name: 'Month Master',
    description: 'Maintain a 30-day streak',
    icon: '⭐',
    target: 30,
    category: 'streak' as const,
    tier: 'silver' as const,
  },
  {
    id: 'two-month-streak',
    name: 'Momentum Builder',
    description: 'Maintain a 60-day streak',
    icon: '🌠',
    target: 60,
    category: 'streak' as const,
    tier: 'silver' as const,
  },
  {
    id: 'century-club',
    name: 'Century Club',
    description: 'Maintain a 100-day streak',
    icon: '💯',
    target: 100,
    category: 'streak' as const,
    tier: 'gold' as const,
  },
  {
    id: 'half-year-hero',
    name: 'Half Year Hero',
    description: 'Maintain a 180-day streak',
    icon: '🎖️',
    target: 180,
    category: 'streak' as const,
    tier: 'platinum' as const,
  },
  {
    id: 'year-legend',
    name: 'Year Legend',
    description: 'Maintain a 365-day streak',
    icon: '👑',
    target: 365,
    category: 'streak' as const,
    tier: 'diamond' as const,
  },
  {
    id: 'perfect-week',
    name: 'Perfect Week',
    description: 'Complete all habits for 7 days straight',
    icon: '✨',
    target: 7,
    category: 'consistency' as const,
    tier: 'silver' as const,
  },
  {
    id: 'perfect-month',
    name: 'Perfect Month',
    description: 'Complete all habits for 30 days straight',
    icon: '🌟',
    target: 30,
    category: 'consistency' as const,
    tier: 'gold' as const,
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Complete habits before 9 AM for 7 days',
    icon: '🌅',
    target: 7,
    category: 'time' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'morning-champion',
    name: 'Morning Champion',
    description: 'Complete habits before 9 AM for 30 days',
    icon: '☀️',
    target: 30,
    category: 'time' as const,
    tier: 'gold' as const,
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Complete habits after 9 PM for 7 days',
    icon: '🦉',
    target: 7,
    category: 'time' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'midnight-warrior',
    name: 'Midnight Warrior',
    description: 'Complete habits after 9 PM for 30 days',
    icon: '🌙',
    target: 30,
    category: 'time' as const,
    tier: 'gold' as const,
  },
  {
    id: 'weekend-warrior',
    name: 'Weekend Warrior',
    description: 'Complete all habits on weekends for 4 weeks',
    icon: '🎉',
    target: 4,
    category: 'consistency' as const,
    tier: 'silver' as const,
  },
  {
    id: 'comeback-kid',
    name: 'Comeback Kid',
    description: 'Restart a habit after missing 3+ days',
    icon: '💫',
    target: 1,
    category: 'resilience' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'phoenix-rising',
    name: 'Phoenix Rising',
    description: 'Rebuild a 30-day streak after breaking it',
    icon: '🔥',
    target: 1,
    category: 'resilience' as const,
    tier: 'gold' as const,
  },
  {
    id: 'multi-tasker',
    name: 'Multi-Tasker',
    description: 'Create 5 different habits',
    icon: '🎭',
    target: 5,
    category: 'variety' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'habit-collector',
    name: 'Habit Collector',
    description: 'Create 10 different habits',
    icon: '📚',
    target: 10,
    category: 'variety' as const,
    tier: 'silver' as const,
  },
  {
    id: 'life-optimizer',
    name: 'Life Optimizer',
    description: 'Create 20 different habits',
    icon: '🎨',
    target: 20,
    category: 'variety' as const,
    tier: 'gold' as const,
  },
  {
    id: 'challenge-accepted',
    name: 'Challenge Accepted',
    description: 'Complete your first challenge',
    icon: '🎖️',
    target: 1,
    category: 'challenge' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'challenge-master',
    name: 'Challenge Master',
    description: 'Complete 5 challenges',
    icon: '🏆',
    target: 5,
    category: 'challenge' as const,
    tier: 'gold' as const,
  },
  {
    id: 'challenge-legend',
    name: 'Challenge Legend',
    description: 'Complete 10 challenges',
    icon: '🥇',
    target: 10,
    category: 'challenge' as const,
    tier: 'platinum' as const,
  },
  {
    id: 'social-butterfly',
    name: 'Social Butterfly',
    description: 'Share your progress 5 times',
    icon: '🦋',
    target: 5,
    category: 'social' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'inspiration-spreader',
    name: 'Inspiration Spreader',
    description: 'Share your progress 20 times',
    icon: '✨',
    target: 20,
    category: 'social' as const,
    tier: 'gold' as const,
  },
  {
    id: 'note-taker',
    name: 'Note Taker',
    description: 'Add notes to 10 habit completions',
    icon: '📝',
    target: 10,
    category: 'reflection' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'thoughtful-tracker',
    name: 'Thoughtful Tracker',
    description: 'Add notes to 50 habit completions',
    icon: '📖',
    target: 50,
    category: 'reflection' as const,
    tier: 'silver' as const,
  },
  {
    id: 'mood-master',
    name: 'Mood Master',
    description: 'Track your mood for 30 days',
    icon: '😊',
    target: 30,
    category: 'reflection' as const,
    tier: 'gold' as const,
  },
  {
    id: 'routine-builder',
    name: 'Routine Builder',
    description: 'Create your first routine',
    icon: '🔄',
    target: 1,
    category: 'routine' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'routine-master',
    name: 'Routine Master',
    description: 'Complete a routine 30 times',
    icon: '⚙️',
    target: 30,
    category: 'routine' as const,
    tier: 'gold' as const,
  },
  {
    id: 'garden-starter',
    name: 'Garden Starter',
    description: 'Plant your first habit in the garden',
    icon: '🌱',
    target: 1,
    category: 'garden' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'green-thumb',
    name: 'Green Thumb',
    description: 'Grow 5 plants to full bloom',
    icon: '🌻',
    target: 5,
    category: 'garden' as const,
    tier: 'silver' as const,
  },
  {
    id: 'master-gardener',
    name: 'Master Gardener',
    description: 'Grow 20 plants to full bloom',
    icon: '🌺',
    target: 20,
    category: 'garden' as const,
    tier: 'platinum' as const,
  },
  {
    id: 'template-explorer',
    name: 'Template Explorer',
    description: 'Use a habit template',
    icon: '🗺️',
    target: 1,
    category: 'exploration' as const,
    tier: 'bronze' as const,
  },
  {
    id: 'category-master',
    name: 'Category Master',
    description: 'Complete habits in 5 different categories',
    icon: '🎯',
    target: 5,
    category: 'variety' as const,
    tier: 'silver' as const,
  },
  {
    id: 'balanced-life',
    name: 'Balanced Life',
    description: 'Complete habits in 10 different categories',
    icon: '⚖️',
    target: 10,
    category: 'variety' as const,
    tier: 'platinum' as const,
  },
  {
    id: 'speed-demon',
    name: 'Speed Demon',
    description: 'Complete 5 habits in one day',
    icon: '⚡',
    target: 1,
    category: 'intensity' as const,
    tier: 'silver' as const,
  },
  {
    id: 'productivity-beast',
    name: 'Productivity Beast',
    description: 'Complete 10 habits in one day',
    icon: '🦁',
    target: 1,
    category: 'intensity' as const,
    tier: 'gold' as const,
  },
  {
    id: 'monthly-champion',
    name: 'Monthly Champion',
    description: 'Complete 100 habits in one month',
    icon: '🏅',
    target: 1,
    category: 'intensity' as const,
    tier: 'platinum' as const,
  },
  {
    id: 'loyal-user',
    name: 'Loyal User',
    description: 'Use the app for 30 days',
    icon: '💝',
    target: 30,
    category: 'loyalty' as const,
    tier: 'silver' as const,
  },
  {
    id: 'dedicated-member',
    name: 'Dedicated Member',
    description: 'Use the app for 100 days',
    icon: '💎',
    target: 100,
    category: 'loyalty' as const,
    tier: 'gold' as const,
  },
  {
    id: 'lifetime-member',
    name: 'Lifetime Member',
    description: 'Use the app for 365 days',
    icon: '🌟',
    target: 365,
    category: 'loyalty' as const,
    tier: 'diamond' as const,
  },
];
