export const ACHIEVEMENT_DEFINITIONS = [
  {
    id: 'first-step',
    name: 'First Step',
    description: 'Complete your first habit',
    icon: '🎯',
    target: 1,
    category: 'completion' as const,
  },
  {
    id: 'week-warrior',
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    target: 7,
    category: 'streak' as const,
  },
  {
    id: 'month-master',
    name: 'Month Master',
    description: 'Maintain a 30-day streak',
    icon: '⭐',
    target: 30,
    category: 'streak' as const,
  },
  {
    id: 'century-club',
    name: 'Century Club',
    description: 'Maintain a 100-day streak',
    icon: '💯',
    target: 100,
    category: 'streak' as const,
  },
  {
    id: 'year-legend',
    name: 'Year Legend',
    description: 'Maintain a 365-day streak',
    icon: '👑',
    target: 365,
    category: 'streak' as const,
  },
  {
    id: 'habit-builder',
    name: 'Habit Builder',
    description: 'Complete 10 total habits',
    icon: '🏗️',
    target: 10,
    category: 'completion' as const,
  },
  {
    id: 'dedication',
    name: 'Dedication',
    description: 'Complete 50 total habits',
    icon: '💪',
    target: 50,
    category: 'completion' as const,
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Complete 100 total habits',
    icon: '🚀',
    target: 100,
    category: 'completion' as const,
  },
  {
    id: 'consistency-king',
    name: 'Consistency King',
    description: 'Complete 500 total habits',
    icon: '👑',
    target: 500,
    category: 'completion' as const,
  },
  {
    id: 'perfect-week',
    name: 'Perfect Week',
    description: 'Complete all habits for 7 days straight',
    icon: '✨',
    target: 7,
    category: 'consistency' as const,
  },
  {
    id: 'perfect-month',
    name: 'Perfect Month',
    description: 'Complete all habits for 30 days straight',
    icon: '🌟',
    target: 30,
    category: 'consistency' as const,
  },
  {
    id: 'early-bird',
    name: 'Early Bird',
    description: 'Complete habits before 9 AM for 7 days',
    icon: '🌅',
    target: 7,
    category: 'consistency' as const,
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    description: 'Complete habits after 9 PM for 7 days',
    icon: '🦉',
    target: 7,
    category: 'consistency' as const,
  },
  {
    id: 'challenge-accepted',
    name: 'Challenge Accepted',
    description: 'Complete your first challenge',
    icon: '🎖️',
    target: 1,
    category: 'challenge' as const,
  },
  {
    id: 'challenge-master',
    name: 'Challenge Master',
    description: 'Complete 5 challenges',
    icon: '🏆',
    target: 5,
    category: 'challenge' as const,
  },
];
